name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Set up MinGW
        # uses: egor-tensin/setup-mingw@v2
        # uses: egor-tensin/setup-mingw@2.2.0
        uses: egor-tensin/setup-mingw@84c781b557efd538dec66bde06988d81cd3138cf
        with:
          platform: x86

      - name: Set tag and directory name env
        run: |
          export tagName=${GITHUB_REF/refs\/tags\//}
          echo "Tag: ${tagName}"
          echo "RELEASE_VERSION=${tagName}" >> $GITHUB_ENV

      - name: Build DLL
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          env CGO_ENABLED=1 \
            GOARCH=386 \
            GOOS=windows \
            CC=i686-w64-mingw32-gcc \
            CGO_CFLAGS="-m32 $CGO_CFLAGS" \
            go build -buildvcs=false -buildmode c-shared -ldflags="-s -w -extldflags=-static" -o .artifacts/twitch-integration.dll ./cmd/twitch-integration/

      - name: Build Connector
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          env CGO_ENABLED=1 GOARCH=386 GOOS=windows go build -buildvcs=false -ldflags="-s -w" -o .artifacts/twitch-integration-connector.exe ./cmd/twitch-integration-connector/

      - name: Calculate distribution hash
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          sha256sum ".artifacts/twitch-integration.dll" > ".artifacts/twitch-integration.dll.sha256"
          cat ".artifacts/twitch-integration.dll.sha256"
          sha256sum ".artifacts/twitch-integration-connector.exe" > ".artifacts/twitch-integration-connector.exe.sha256"
          cat ".artifacts/twitch-integration-connector.exe.sha256"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            .artifacts/twitch-integration.dll
            .artifacts/twitch-integration.dll.sha256
            .artifacts/twitch-integration-connector.exe
            .artifacts/twitch-integration-connector.exe.sha256

      - name: Create github release
        run: |
          gh release create $RELEASE_VERSION --generate-notes .artifacts/twitch-integration.dll .artifacts/twitch-integration.dll.sha256 .artifacts/twitch-integration-connector.exe .artifacts/twitch-integration-connector.exe.sha256
          exit 0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
